# Autogenerated wrapper script for Clingcon_jll for x86_64-w64-mingw32-cxx03
export clingcon, libclingcon

using Clingo_jll
JLLWrappers.@generate_wrapper_header("Clingcon")
JLLWrappers.@declare_executable_product(clingcon)
JLLWrappers.@declare_library_product(libclingcon, "libclingcon.dll")
function __init__()
    JLLWrappers.@generate_init_header(Clingo_jll)
    JLLWrappers.@init_executable_product(
        clingcon,
        "bin\\clingcon.exe",
    )

    JLLWrappers.@init_library_product(
        libclingcon,
        "bin\\libclingcon.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
